In [1]:
import pandas as pd

# 景区评论

In [2]:
scenic_comment = pd.read_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/景区评论.CSV",encoding='gbk')

In [3]:
scenic_comment

      景区名称        评论日期                                               评论内容
0      A01  2020-06-16  是亲子游的绝佳场所，门票就是有点贵，不过可以接受，爷爷奶奶不放心小朋友也跟上来了，当天我们十...
1      A01  2020-01-23  **景区差不多，票价偏贵了。大马戏比较精彩，八点的场次，6点40才能检票进入，我们6点多看看...
2      A01  2020-03-22  很有**特色的亲子酒店，房间里的装修很可爱，小孩子特别喜欢，洗漱用品也很有特色，对应的房间还...
3      A01  2020-12-25  有园区的工作人员在那，他会主动给你园区里的地图和表演的时间安排，很周到，上接驳车大概也是34...
4      A01  2020-11-28  周五逃课跟朋友在广州集合！终于如愿以偿的到达欢乐世界。学生票198 需要出示相关证件（校卡或...
...    ...         ...                                                ...
59101  A50  2015-02-25  还好吧。我们刚刚到瀑布楼遇到一点小意外，打电话到景区办公室要求帮助，景区值班领导马上行动，在...
59102  A50  2015-02-25                               山高路远，走的很辛苦。景色宜人爬山很累。
59103  A50  2015-02-22                           环境很好，空气非常棒，很适合全家旅游，特别是避暑
59104  A50  2015-02-16                                都很方便，价格实惠吧，可以预早就订好。
59105  A50  2015-02-22                        旅行社不负责任 到了景点没有与门票售票协调好 等了很久

[59106 rows x 3 columns]

In [4]:
#无缺失值
#438条重复值（不管日期）
scenic_comment[['景区名称','评论内容']].duplicated().sum()

438

In [5]:
#查看部分重复值
scenic_comment[['景区名称','评论内容']][scenic_comment.duplicated()]

      景区名称                                               评论内容
278    A01  The entire resort area is quite large, includi...
286    A01  The entire resort area is quite large, includi...
290    A01  The Chimelong Happy World is worth a visit. Th...
293    A01  The Chimelong Happy World is worth a visit. Th...
320    A01  首先停车场入口和出口的标示不是很清楚，本来是从北门进的，下午出去的时候绕了很久才绕了出去还跑...
...    ...                                                ...
58189  A47  建议大家不要去玩，景区小还坑爹，存在严重的安全隐患，我们一家老小去玩，在音乐餐厅门口休息，突...
58463  A48  五台山是世界文化遗产，夏天是比较好的旅游季节。旺季门票168元，淡季140元，都不包含观光车...
58578  A48                                 换票有些慢，人真心很多，其他挺好的。
58731  A49  相对藏龙百瀑，它的人要少很多，但正因如此，更显清幽。我们开始几乎是包山游玩，很是尽兴。后来才...
59018  A50                                    非常不错，山清水秀，玩得开心！

[305 rows x 2 columns]

In [6]:
#删除重复值
scenic_comment.drop_duplicates(subset={'景区名称','评论内容'},keep="first",inplace=True)
scenic_comment.reset_index(inplace=True)
scenic_comment.drop(labels=['index'],axis=1,inplace=True)

In [7]:
scenic_comment

      景区名称        评论日期                                               评论内容
0      A01  2020-06-16  是亲子游的绝佳场所，门票就是有点贵，不过可以接受，爷爷奶奶不放心小朋友也跟上来了，当天我们十...
1      A01  2020-01-23  **景区差不多，票价偏贵了。大马戏比较精彩，八点的场次，6点40才能检票进入，我们6点多看看...
2      A01  2020-03-22  很有**特色的亲子酒店，房间里的装修很可爱，小孩子特别喜欢，洗漱用品也很有特色，对应的房间还...
3      A01  2020-12-25  有园区的工作人员在那，他会主动给你园区里的地图和表演的时间安排，很周到，上接驳车大概也是34...
4      A01  2020-11-28  周五逃课跟朋友在广州集合！终于如愿以偿的到达欢乐世界。学生票198 需要出示相关证件（校卡或...
...    ...         ...                                                ...
58663  A50  2015-02-25  还好吧。我们刚刚到瀑布楼遇到一点小意外，打电话到景区办公室要求帮助，景区值班领导马上行动，在...
58664  A50  2015-02-25                               山高路远，走的很辛苦。景色宜人爬山很累。
58665  A50  2015-02-22                           环境很好，空气非常棒，很适合全家旅游，特别是避暑
58666  A50  2015-02-16                                都很方便，价格实惠吧，可以预早就订好。
58667  A50  2015-02-22                        旅行社不负责任 到了景点没有与门票售票协调好 等了很久

[58668 rows x 3 columns]

# 酒店评论

In [8]:
hotel_comment = pd.read_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/酒店评论.CSV",encoding='gbk')

In [9]:
hotel_comment

,酒店名称,评论日期,评论内容,入住房型
0,H01,2020-01-01,酒店很适合家庭出行,标准客房
1,H01,2020-01-01,升级了房间 延迟退房 很赞,标准客房
2,H01,2020-01-01,这几年，每年都会来广州，每次都会住**酒店。因为位置好，酒店的性价比也不错，这次给免费升级了...,标准客房
3,H01,2020-01-01,酒店很好不错,标准客房
4,H01,2020-01-01,超五星好评,高级客房
...,...,...,...,...
25220,H50,2020-08-24,酒店是老字号宾馆，虽然有装修过但设施比较陈旧房间空调比较小，卫生间里的墙壁有剥落现象，浴室的...,高级双床房
25221,H50,2020-08-24,本人觉得还好，价格偏高，没有很高档，服务是很好，设施偏老，也不会很大，喜欢楼下的早茶。,高级大床房
25222,H50,2020-08-24,隔音极差，睡眠让人崩溃。,高级大床房
25223,H50,2020-08-25,酒店位置很好，停车场比较小。,高级双床房
25224,H50,2020-08-25,位置好找，停车方便，酒店太老了！,高级双床房

In [10]:
#行列均无缺失值
hotel_comment.isnull().any(axis=1).sum()

0

In [11]:
#445条重复值（不管日期）
hotel_comment[['酒店名称','评论内容','入住房型']].duplicated().sum()

445

In [12]:
#查看部分重复值
hotel_comment[['酒店名称','评论内容','入住房型']][hotel_comment.duplicated()]

      酒店名称                                               评论内容   入住房型
143    H01                                             早餐不错??   标准客房
144    H01                                             早餐不错??   标准客房
173    H01                                            交通便捷近东站   标准客房
414    H01                                            酒店很好不错的  标准大床房
667    H01                                             好评！好评！  标准大床房
...    ...                                                ...    ...
24919  H49                                      很不错，李静、张宏鑫服务好  高级大床房
24921  H49                                      很不错，李静、张宏鑫服务好  高级大床房
24922  H49                                      很不错，李静、张宏鑫服务好  高级大床房
25001  H50  老牌星级酒店，房间内设施有点老了，服务还不错，酒店位置还不错，属于市中心的位置，旁边有机场大...  高级双床房
25037  H50                                               感觉不错  乐享大床房

[248 rows x 3 columns]

In [13]:
#删除重复值（不管日期）
hotel_comment.drop_duplicates(subset={'酒店名称','评论内容','入住房型'},keep="first",inplace=True)
hotel_comment.reset_index(inplace=True)
hotel_comment.drop(labels=['index'],axis=1,inplace=True)

In [14]:
hotel_comment

,酒店名称,评论日期,评论内容,入住房型
0,H01,2020-01-01,酒店很适合家庭出行,标准客房
1,H01,2020-01-01,升级了房间 延迟退房 很赞,标准客房
2,H01,2020-01-01,这几年，每年都会来广州，每次都会住**酒店。因为位置好，酒店的性价比也不错，这次给免费升级了...,标准客房
3,H01,2020-01-01,酒店很好不错,标准客房
4,H01,2020-01-01,超五星好评,高级客房
...,...,...,...,...
24775,H50,2020-08-24,酒店是老字号宾馆，虽然有装修过但设施比较陈旧房间空调比较小，卫生间里的墙壁有剥落现象，浴室的...,高级双床房
24776,H50,2020-08-24,本人觉得还好，价格偏高，没有很高档，服务是很好，设施偏老，也不会很大，喜欢楼下的早茶。,高级大床房
24777,H50,2020-08-24,隔音极差，睡眠让人崩溃。,高级大床房
24778,H50,2020-08-25,酒店位置很好，停车场比较小。,高级双床房
24779,H50,2020-08-25,位置好找，停车方便，酒店太老了！,高级双床房

# 景区评分

In [15]:
scenic_rating = pd.read_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/景区评分.CSV",encoding='gbk')

In [16]:
scenic_rating.drop(labels=['Unnamed: 7'],axis=1,inplace=True)

In [17]:
scenic_rating

   景区名称  总得分  服务得分  位置得分  设施得分  卫生得分  性价比得分
0   A01  4.4   3.8   4.9   4.9   4.5    4.5
1   A02  4.2   3.8   4.9   4.2   4.5    4.0
2   A03  4.2   3.9   4.2   4.1   4.5    4.5
3   A04  4.2   3.8   4.0   4.0   4.5    4.5
4   A05  4.2   3.9   4.9   4.0   4.5    4.2
5   A06  4.5   4.3   4.7   4.0   4.9    4.6
6   A07  4.4   3.9   4.9   4.0   4.9    4.4
7   A08  4.2   3.8   4.9   4.9   4.0    4.5
8   A09  4.3   3.9   4.9   4.5   4.5    4.4
9   A10  4.3   3.8   4.0   4.2   4.9    4.5
10  A11  4.1   3.9   4.9   4.0   4.0    4.2
11  A12  4.5   4.0   4.9   4.9   4.9    4.0
12  A13  4.5   4.5   4.9   4.5   4.5    4.5
13  A14  4.4   3.9   4.2   4.5   4.9    4.5
14  A15  4.4   3.9   4.9   4.5   4.9    4.0
15  A16  4.5   3.9   4.9   4.5   4.9    4.8
16  A17  4.5   3.9   4.9   4.9   4.9    4.5
17  A18  4.3   3.9   4.0   4.5   4.5    4.9
18  A19  4.3   3.9   4.9   4.0   4.5    4.4
19  A20  4.4   3.9   4.9   4.0   4.9    4.5
20  A21  4.6   4.0   4.9   4.5   4.9    4.8
21  A22  4.4   3.8   4.9   4.5   4.9    4.2
22  A23  4.8   4.9   4.9   4.9   4.9    4.0
23  A24  4.3   3.9   4.9   4.0   4.2    4.9
24  A25  4.5   4.3   4.9   4.0   4.5    4.8
25  A26  4.5   3.9   4.9   4.5   4.9    4.5
26  A27  4.2   3.8   4.9   4.0   4.2    4.5
27  A28  4.4   4.0   4.0   4.5   4.9    4.5
28  A29  4.4   3.9   4.9   4.5   4.9    4.0
29  A30  4.5   3.9   4.9   4.0   4.9    4.9
30  A31  4.3   3.9   4.0   4.5   4.5    4.5
31  A32  4.3   4.0   4.9   4.9   4.2    4.4
32  A33  4.5   3.9   4.9   4.5   4.9    4.5
33  A34  4.4   3.9   4.9   4.5   4.9    4.2
34  A35  4.6   4.0   4.9   4.9   4.9    4.5
35  A36  4.6   3.9   4.9   4.9   4.9    4.8
36  A37  4.7   4.9   4.9   4.9   4.2    4.8
37  A38  4.8   4.9   4.9   4.5   4.9    4.9
38  A39  4.9   4.9   4.9   4.9   4.9    4.8
39  A40  4.6   4.0   4.9   4.9   4.9    4.9
40  A41  4.3   4.0   4.2   4.1   4.5    4.5
41  A42  4.3   4.0   4.9   4.9   4.0    4.8
42  A43  4.3   3.9   4.9   4.0   4.5    4.5
43  A44  4.6   3.9   4.9   4.9   4.9    4.9
44  A45  4.6   3.9   4.9   4.9   4.9    4.6
45  A46  4.5   3.9   4.9   4.5   4.9    4.4
46  A47  4.4   3.8   4.9   4.0   4.9    4.5
47  A48  4.6   4.2   4.9   4.2   4.9    4.8
48  A49  4.6   3.9   4.9   4.9   4.9    4.9
49  A50  4.6   3.9   4.9   4.9   4.9    4.8

# 酒店评分

In [18]:
hotel_rating = pd.read_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/景区评分.CSV",encoding='gbk')

In [19]:
hotel_rating.drop(labels=['Unnamed: 7'],axis=1,inplace=True)

In [20]:
hotel_rating

   景区名称  总得分  服务得分  位置得分  设施得分  卫生得分  性价比得分
0   A01  4.4   3.8   4.9   4.9   4.5    4.5
1   A02  4.2   3.8   4.9   4.2   4.5    4.0
2   A03  4.2   3.9   4.2   4.1   4.5    4.5
3   A04  4.2   3.8   4.0   4.0   4.5    4.5
4   A05  4.2   3.9   4.9   4.0   4.5    4.2
5   A06  4.5   4.3   4.7   4.0   4.9    4.6
6   A07  4.4   3.9   4.9   4.0   4.9    4.4
7   A08  4.2   3.8   4.9   4.9   4.0    4.5
8   A09  4.3   3.9   4.9   4.5   4.5    4.4
9   A10  4.3   3.8   4.0   4.2   4.9    4.5
10  A11  4.1   3.9   4.9   4.0   4.0    4.2
11  A12  4.5   4.0   4.9   4.9   4.9    4.0
12  A13  4.5   4.5   4.9   4.5   4.5    4.5
13  A14  4.4   3.9   4.2   4.5   4.9    4.5
14  A15  4.4   3.9   4.9   4.5   4.9    4.0
15  A16  4.5   3.9   4.9   4.5   4.9    4.8
16  A17  4.5   3.9   4.9   4.9   4.9    4.5
17  A18  4.3   3.9   4.0   4.5   4.5    4.9
18  A19  4.3   3.9   4.9   4.0   4.5    4.4
19  A20  4.4   3.9   4.9   4.0   4.9    4.5
20  A21  4.6   4.0   4.9   4.5   4.9    4.8
21  A22  4.4   3.8   4.9   4.5   4.9    4.2
22  A23  4.8   4.9   4.9   4.9   4.9    4.0
23  A24  4.3   3.9   4.9   4.0   4.2    4.9
24  A25  4.5   4.3   4.9   4.0   4.5    4.8
25  A26  4.5   3.9   4.9   4.5   4.9    4.5
26  A27  4.2   3.8   4.9   4.0   4.2    4.5
27  A28  4.4   4.0   4.0   4.5   4.9    4.5
28  A29  4.4   3.9   4.9   4.5   4.9    4.0
29  A30  4.5   3.9   4.9   4.0   4.9    4.9
30  A31  4.3   3.9   4.0   4.5   4.5    4.5
31  A32  4.3   4.0   4.9   4.9   4.2    4.4
32  A33  4.5   3.9   4.9   4.5   4.9    4.5
33  A34  4.4   3.9   4.9   4.5   4.9    4.2
34  A35  4.6   4.0   4.9   4.9   4.9    4.5
35  A36  4.6   3.9   4.9   4.9   4.9    4.8
36  A37  4.7   4.9   4.9   4.9   4.2    4.8
37  A38  4.8   4.9   4.9   4.5   4.9    4.9
38  A39  4.9   4.9   4.9   4.9   4.9    4.8
39  A40  4.6   4.0   4.9   4.9   4.9    4.9
40  A41  4.3   4.0   4.2   4.1   4.5    4.5
41  A42  4.3   4.0   4.9   4.9   4.0    4.8
42  A43  4.3   3.9   4.9   4.0   4.5    4.5
43  A44  4.6   3.9   4.9   4.9   4.9    4.9
44  A45  4.6   3.9   4.9   4.9   4.9    4.6
45  A46  4.5   3.9   4.9   4.5   4.9    4.4
46  A47  4.4   3.8   4.9   4.0   4.9    4.5
47  A48  4.6   4.2   4.9   4.2   4.9    4.8
48  A49  4.6   3.9   4.9   4.9   4.9    4.9
49  A50  4.6   3.9   4.9   4.9   4.9    4.8

# 导出数据

In [21]:
scenic_comment.to_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/清洗过的数据/景区评论.csv",encoding='gbk',index=False)
hotel_comment.to_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/清洗过的数据/酒店评论.csv",encoding='gbk',index=False)
scenic_rating.to_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/清洗过的数据/景区评分.csv",encoding='gbk',index=False)
hotel_rating.to_csv("E:/泰迪杯/数据挖掘2021/C/C题数据/清洗过的数据/酒店评分.csv",encoding='gbk',index=False)